services:
  frontend-api:
    build:
      context: ./frontend-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/frontend_library
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis

  backend-api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/backend_library
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
    driver: local
